schema_version = "1.0.0"

id = "ice_cube_rig_jabe"
version = "2.0.4"
name = "Ice Cube Rig Jabe Edit"
tagline = "UI and backend addon for the Minecraft Ice Cube Rig!"
maintainer = "DarthLilo (Jabe Edit)"

type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Local skin and preset management"